### ISSUE TITLE
stickerfy/seed/product-seeder.js - happy image no longer available

### ISSUE THREAD

**Issue by tcd1558** [meaghanlewis/stickerfy#10]
./test/unit/cart.spec.js
        "imagePath": "https://buildahead.com/wp-content/uploads/2017/02/happy-emoji-smaller.png",
        
Above image is no longer provided by buildahead.com (under that link?). 
Alternative: 
https://cdn.shopify.com/s/files/1/1061/1924/products/Emoji_Icon_-_Happy_large.png?v=1571606093

Yet, this is only a quick fix, not a solution. Shopify can modify the link to above image at anytime. 
A permanent solution would be to add simple, copyright free images within the repository.

**Comment by meaghanlewis** [comment]
@tcd1558 thank you for letting me know about this! This issue has been fixed in 330652ab86004a538d1662c8759f3788826b8984
