### ISSUE TITLE
Depreciated Mongoose Connect Option in product-seeder.js

### ISSUE THREAD

**Issue by rquinones93** [meaghanlewis/stickerfy#2]
I believe line 5 in product-seeder.js should be updated with the following

`mongoose.connect('mongodb://localhost:27017/shopping', { useNewUrlParser: true });`

I was unable to seed the database while running the seed command and was met with a message saying `useMongoClient` was depreciated and to switch to `useNewUrlParser` - the change then worked on my local environment.

Here is the error message
`WARNING: The `useMongoClient` option is no longer necessary in mongoose 5.x, please remove it.`

...

`(node:6774) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.`

I would've made a PR but did not have rights to do so, thanks.

**Comment by richardazia** [comment]
(node:56413) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html The error message was updated. 

I had to install bluebird (npm i bluebird) and add "mongoose.Promise = require('bluebird');"  to product-seeder.js
