### ISSUE TITLE
Unable to clone repository

### ISSUE THREAD

**Issue by smithdr5** [meaghanlewis/stickerfy#8]
Hi Meaghan, after copying: ' git clone https://github.com/meaghanlewis/stickerfy.git ' into iTerm, I keep either getting one of two errors:

1.  ~ % git clone https://github.com/meaghanlewis/stickerfy.git
fatal: destination path 'stickerfy' already exists and is not an empty directory.

2. I'll be prompted for my username and password, and upon entering, it'll say "Directory not found" or something of that sort.

I am fairly new to running tests via the command line, is there something that I am doing wrong?

**Comment by tcd1558** [comment]
Linux, MacOS, or Windows? 
Isn't the message saying the directory already exists on your system? 
E.g.: ~/git/stickerfy

**Comment by meaghanlewis** [comment]
Sorry for not seeing this issue and responding sooner! This sounds like it's likely some kind of problem with git clone and the way you're using it, not a problem with this repository itself.
